/*
 * File: app/store/Events.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Agenda.store.Events', {
    extend: 'Ext.data.Store',

    requires: [
        'Agenda.model.Event'
    ],

    config: {
        data: [
            {
                name: 'Daily checkin',
                rrule: 'FREQ=DAILY;DTSTART=20130201T180000Z;BYDAY=MO,TU,WE,TH,FR',
                duration: 900000
            },
            {
                name: 'Monthly mid-month meeting',
                rrule: 'FREQ=MONTHLY;WKST=MO;BYMONTHDAY=15',
                duration: 1800000
            },
            {
                name: 'Ping-pong tournament',
                rrule: 'FREQ=DAILY;DTSTART=20130801T200000Z;COUNT=1',
                duration: 3600000
            }
        ],
        model: 'Agenda.model.Event',
        storeId: 'Events'
    }
});