/*
 * File: app/controller/Navigation.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Agenda.controller.Navigation', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            eventList: 'eventlist'
        },

        control: {
            "eventlist": {
                initialize: 'start'
            }
        }
    },

    start: function(component, eOpts) {
        // Because we're going to make "ghost" events (for recurring events), we need
        // to build up the list's data by hand. I'll walk you through it.
        
        // First, we grab the variables we need.
        var DAYS_AHEAD = 60,
            realEvents = Ext.getStore('Events'),
            eventListComponent = this.getEventList(),
            events = [],
            today,
            i,
            dayStart,
            dayEnd,
            eventsToday = [];
        
        // What was the first moment of today?
        today = new Date();
        today.setHours(0);
        today.setMinutes(0);
        today.setSeconds(0);
        today.setMilliseconds(0);
        
        // Now, we'll go through each day and see if the events happen.
        for (var i = 0; i < DAYS_AHEAD; i ++) {
        
        	// What's the start and the end of the day we're looking at?
            dayStart = Ext.Date.add(today, Ext.Date.DAY, i);
            dayEnd = Ext.Date.add(dayStart, Ext.Date.DAY, 1);
        
            // Check every event: does the event occur on this day?
            eventsToday.length = 0; // clear it out
            realEvents.each(function(realEvent) {
                if (realEvent.occursBetween(dayStart, dayEnd)) {
        
                    var start = Ext.Date.clone(dayStart),
                        originalStart = realEvent.getStartTime();
                    start.setHours(originalStart.getHours());
                    start.setMinutes(originalStart.getMinutes());
                    start.setSeconds(originalStart.getSeconds());
                    start.setMilliseconds(originalStart.getMilliseconds());
        
                    eventsToday.push({
        				realEvent: realEvent,
        				name: realEvent.get('name'),
        				start: start,
                        duration: humanizeDuration(realEvent.get('duration'))
                    });
        
                }
            });
        
            // Sort the events today by time.
            // TODO
        
            // Add today's events to our "ghost" list.
            // TODO there's a better way to do this
            eventsToday.forEach(function(event) {
                events.push(event);
            });
            console.log(events);
        
        }
        
        // And finally, let's dump the stuff into the view.
        eventListComponent.setData(events);
    }

});