/*
 * File: app/model/Event.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Agenda.model.Event', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                allowNull: false,
                name: 'name',
                type: 'string'
            },
            {
                allowNull: false,
                name: 'rrule',
                type: 'string'
            },
            {
                allowNull: false,
                name: 'duration',
                type: 'int'
            }
        ]
    },

    occursBetween: function(start, end) {
        var rrule = RRule.fromString(this.get('rrule')),
            between = rrule.between(start, end);
        return between.length !== 0;
    },

    getStartTime: function() {
        var rrule = RRule.fromString(this.get('rrule'));
        return rrule.options.dtstart;
    }

});